### ISSUE TITLE
Incorrect origins

### ISSUE THREAD

**Issue by toynbeeidea** [simoninns/DomesdayDuplicator-Case#2]
Tried ordering a set off of Treatstock, got the following message:

"The vendor says that the files have incorrect origins so MMU parts are misaligned. Do you have an ability to fix the models?"

**Comment by simoninns** [comment]
I'm not really sure what they mean... PrusaSlicer has no issues with it (and I've printed 4 mutli-material cases on my MMU2S based Prusa i3).  Of course, the full OpenSCAD source is available (so you can produce any STL files you like) - but, if I understood the issue clearly, I'd probably be able to fix it; so, if possible, ask them for more details please.

Here are the STLs from the repo loaded into the slicer (I just did this to check) - no reported errors:

![prusa](https://user-images.githubusercontent.com/1068814/79863165-9046fc80-83d7-11ea-8678-e944a980fefd.png)

**Comment by gmccauley** [comment]
It looks like Treatstock must manipulate the files somehow when uploading them (resetting the origins to the absolute middle of the object, thus the mis-alignment).  See screenshot below of what it looks like when loading the files provided via Treatstock into PrusaSlicer.  I have confirmed that loading the files located in the repo are aligned correctly.

@toynbeeidea - If you contact me directly (george at grm-3d.com) I can give you a little better price than through Treatstock.

![image](https://user-images.githubusercontent.com/11580087/79865890-8efadd00-83a1-11ea-9f08-ff21fe6b06f2.png)

**Comment by simoninns** [comment]
I'm not really sure how to 'correct' it so that doesn't happen.  In OpenSCAD the materials are simply 'excluded' to make the various STL files, so their location in 3D space should be correct (the lid should be flipped 180 degrees in the slicer to lay flat though - which is shown in the included .3mf files).

**Comment by toynbeeidea** [comment]
I guess really its Treatstock's error, not really anything to do with the files themselves. Maybe worth a note of warning on the front page though?
